### ISSUE TITLE
Vignetting correction / ApplyColorModification() not implemented

### ISSUE THREAD

**Issue by paulparneix** [letmaik/lensfunpy#18]
the new issue as asked in #17
It would be nice to have the ability to use Lensfun ApplyColorModification() function in Lensfunpy.

**Comment by MarekRzewuski** [comment]
Hello,
Has this issue been solved? Is it possible to correct vignetting using lensfunpy?

**Comment by letmaik** [comment]
@MarekRzewuski This issue is still open, so no. A quick search yields the same result: https://github.com/letmaik/lensfunpy/search?q=ApplyColorModification

**Comment by MarekRzewuski** [comment]
Thanks for reply! Is it difficult to implement? 
I would gladly help, but I even don't know where to begin. Could you push me in right direction?

**Comment by dschneiderch** [comment]
I'm also interested in vignetting correction capabilities. unfortunately the interface with c libs is a bit beyond me but id be happy to test!

**Comment by letmaik** [comment]
I implemented this and will do a new release soon.

Example:
```py
cam_maker = 'NIKON CORPORATION'
cam_model = 'NIKON D3S'
lens_maker = 'Nikon'
lens_model = 'Nikkor AF 20mm f/2.8D'
focal_length = 20
aperture = 4
distance = 10
width = 4256
height = 2832

db = lensfun.Database()
cam = db.find_cameras(cam_maker, cam_model)[0]
lens = db.find_lenses(cam, lens_maker, lens_model)[0]

mod = lensfun.Modifier(lens, cam.crop_factor, width, height)
mod.initialize(focal_length, aperture, distance)

img = np.zeros((height, width, 3), np.uint8)
img[:] = 127
mod.apply_color_modification(img) # returns true if applied, otherwise false, e.g. if calibrations missing

import imageio
imageio.imwrite('corrected.png', img)
```
![vignetting corrected test image](https://user-images.githubusercontent.com/530988/97056579-3b9c5e00-1581-11eb-8e16-7ea000ee4ef1.png)

**Comment by MarekRzewuski** [comment]
Thank you! Your make our lives so much easier to live! :+1:

**Comment by letmaik** [comment]
New release 1.8.0 is out. Please give it a try and report any issues.

**Comment by MarekRzewuski** [comment]
I have problems with getting this to work. 
mod.apply_color_modification() is returning false. 
What am I missing here?:

import sys
import lensfunpy as lensfun
import numpy as np
import imageio

cam_maker = 'NIKON CORPORATION'
cam_model = 'NIKON 1 J5'
lens_maker = 'Nikon'
lens_model = 'Nikkor AF-S 70-300mm f/4.5-5.6G VR IF-ED'

focal_length = 300.0
aperture = 7.1
distance = 1000

db = lensfun.Database()
cam = db.find_cameras(cam_maker, cam_model)[0]
lens = db.find_lenses(cam, lens_maker, lens_model)[0]
width = 5568
height = 3712

print(lensfun.__version__)
print(cam)
print(lens)

mod = lensfun.Modifier(lens, cam.crop_factor, width, height)
mod.initialize(focal_length, aperture, distance)

img = np.zeros((height, width, 3), np.uint8)
img[:] = 127
print("MOD:",mod.apply_color_modification(img))

imageio.imwrite("out.tif", img)

Output:
1.8.0
Camera(Maker: Nikon Corporation; Model: Nikon 1 J5; Mount: Nikon CX; Crop Factor: 2.7269999980926514; Score: 825241648)
Lens(Maker: Nikon; Model: Nikon AF-S VR Zoom-Nikkor 70-300mm f/4.5-5.6G IF-ED; Type: RECTILINEAR; Focal: 70.0-300.0; Aperture: 4.5-None; Crop factor: 1.0; Score: 91)
MOD: False

thanks!

**Comment by letmaik** [comment]
@MarekRzewuski The lens model you use does not have vignetting calibrations available: https://github.com/lensfun/lensfun/blob/2849b4bfd13b6b7501495fb841addb8441e0f5ea/data/db/slr-nikon.xml#L2312-L2332

**Comment by MarekRzewuski** [comment]
ah, thank you!
