### ISSUE TITLE
distance --> unit?

### ISSUE THREAD

**Issue by creimers** [letmaik/lensfunpy#19]
What's the unit of `distance`?

**Comment by letmaik** [comment]
Meters I guess, see the docs of libraw.

**Comment by abubelinha** [comment]
I guess you meant this, @letmaik?  It took me a while to find it.
https://lensfun.github.io/manual/latest/structlfModifier.html#a0d97cd8c20f05f54d79af092edca9e1a

I'd suggest adding some links for better understanding the code examples in README.md
```Python
mod.initialize(focal_length, aperture, distance)
```

Thanks a lot for this great package
@abubelinha
