### ISSUE TITLE
Database version is 2, but supported is only 1!

### ISSUE THREAD

**Issue by kvinicki** [letmaik/lensfunpy#20]
Hi, I am getting following error:

** (process:3908): WARNING **: 22:28:25.364: [Lensfun] mil-sony.xml:3:1: Database version is 2, but supported is only 1!

Traceback (most recent call last):
  File "correction.py", line 15, in <module>
    db = lensfunpy.Database(paths = xml)
  File "lensfunpy/_lensfun.pyx", line 230, in lensfunpy._lensfun.Database.__init__
  File "lensfunpy/_lensfun.pyx", line 966, in lensfunpy._lensfun.handleError
lensfunpy._lensfun.XMLFormatError

**Comment by letmaik** [comment]
Without saying what you're trying to do I can't help you much. I'll try anyway and take a best guess...

I assume you downloaded some lensfun xml database files from the current development version of lensfun and now you're trying to load them with lensfunpy. The development version is at database version 2, however the last stable version of lensfun (0.3.2) is at 1, and the latter is what lensfunpy is based on at the moment.

Having said that, there's a pre-release version of lensfunpy out which I think is reasonably up-to-date to already support v2. Give it a try: https://pypi.org/project/lensfunpy/1.7.0a2/

**Comment by kvinicki** [comment]
You are right :) Everything works great with your latest version. Thanks for quick reply.
