### ISSUE TITLE
Wheel for Python 3.7

### ISSUE THREAD

**Issue by StefanRiechelmann** [letmaik/lensfunpy#21]
Dear Maik,

if you still support lensfunpy - could you please extend the provided wheels to Python 3.7? I tried to compile it myself but failed miserably :)

Greetings

Stefan

**Comment by letmaik** [comment]
Sure, just need a bit of time to fix the build setup that's currently broken on Windows.

**Comment by letmaik** [comment]
Version 1.6.1 is released now and has Python 3.7 wheels.

**Comment by StefanRiechelmann** [comment]
Works like a charm, ty Maik!
