### ISSUE TITLE
Differences between Hugin and Lensfunpy

### ISSUE THREAD

**Issue by JakeForsey** [letmaik/lensfunpy#22]
I'm attempting to recreate a lens distortion correction that I've achieved in Hugin Lens calibration GUI whilst using lensfunpy, there seems to be a slight discrepancy between the two approaches that I can't account for.

The raw image: 
![image](https://user-images.githubusercontent.com/15824258/57462315-8a144a80-7270-11e9-88aa-2c7b27a67fa3.jpg)

The lens distortion correction parameters and output in Hugin Lens calibration GUI:
![Screenshot from 2019-05-09 15-39-29](https://user-images.githubusercontent.com/15824258/57462389-aadca000-7270-11e9-94e6-6d816ddcbec0.png)

focal length 8
focal length multiplier 3.97

a 0.00199
b -0.04563
c -0.02328

The lens distortion correction output from lensfunpy:
![undistorted_image](https://user-images.githubusercontent.com/15824258/57462613-145cae80-7271-11e9-9d1d-f9e536f2d0c1.jpg)

My python script:
```
import lensfunpy
import lensfunpy.util

import cv2

IMAGE = "/home/gsi/Downloads/image.jpg"
SHOW_IMAGE = False
XML = """
<lensdatabase>
    <camera>
        <maker>MAKER</maker>
        <model>MODEL</model>
        <mount>djiFC6310</mount>
        <cropfactor>3.97</cropfactor>
    </camera>
    
    <lens>
        <maker>MAKER</maker>
        <model>MODEL</model>
        <mount>djiFC6310</mount>
        <cropfactor>3.97</cropfactor>
        <calibration>
            <distortion model="ptlens" focal="8.0" a="0.00199" b="-0.04563" c="-0.02328"/>
        </calibration>
    </lens>
</lensdatabase>

"""

image = cv2.imread(IMAGE)

db = lensfunpy.Database(xml=XML)
cam = db.find_cameras("MAKER", "MODEL")[0]
lens = db.find_lenses(cam, "MAKER", "MODEL")[0]

print(cam)
print(lens)

height, width = image.shape[0], image.shape[1]

mod = lensfunpy.Modifier(lens, cam.crop_factor, width, height)
mod.initialize(
    8.0, 
    1.4
)

undistorted_coords = mod.apply_geometry_distortion()   
undistorted_image = lensfunpy.util.remap(image, undistorted_coords)

cv2.imwrite("undistorted_image.jpg", undistorted_image)
```

The differences are small, but seem significant to my eye!

Any help greatly appreciated.

**Comment by letmaik** [comment]
To figure out whether this is a lensfunpy or lensfun issue, can you try to undistort your image with another software that uses lensfun? See http://lensfun.sourceforge.net/usage/.

**Comment by JakeForsey** [comment]
Thanks for the speedy response. Yes, good idea.
