### ISSUE TITLE
Package license with distro

### ISSUE THREAD

**Issue by mwilson8** [letmaik/lensfunpy#23]
Can you make a release on pypi that includes the license file please

**Comment by letmaik** [comment]
@mwilson8 I will bundle the LICENSE file with the wheels from now on, but I won't release sdists anymore on PyPI. You probably want to modify the conda-forge recipe to instead checkout the right version tag of this repo. I'll release a new lensfunpy version (1.6.2) very soon, mostly for Python 3.8 wheels.
