### ISSUE TITLE
submodules not reachable

### ISSUE THREAD

**Issue by haraldsteinlechner** [letmaik/lensfunpy#24]
whenever submodules are needed the build fails due to: https://github.com/letmaik/lensfunpy/blob/master/.gitmodules#L3
```
git clone git://git.code.sf.net/p/lensfun/code
Cloning into 'code'...
fatal: remote error: access denied or repository not exported: /p/lensfun/code
```

is this situation known or just temporary outage?

PS.: i found it when working with python 3.8 where the install process could not find precompiled binaries and started cloning submodules

EDIT: ah very related to: https://github.com/letmaik/lensfunpy/issues/21

**Comment by letmaik** [comment]
I fixed the submodule url in master. Note that this will not work with the sdist from pypi. I will release a new version in a while but for now I suggest you stick to Python 3.7.

**Comment by letmaik** [comment]
Note that lensfunpy 1.7.0 is out now which has python 3.8 wheels.

**Comment by haraldsteinlechner** [comment]
awesome. thanks!
