### ISSUE TITLE
source files missing on pypi

### ISSUE THREAD

**Issue by Anthchirp** [letmaik/lensfunpy#25]
There is no sdist (.tar.gz) uploaded on pypi, which is why the most recent version is not being picked up by the conda-forge autoupdater bot.

**Comment by letmaik** [comment]
This is on purpose, to prevent pip from trying to build from source, which in most cases will fail. People on unsupported platforms would hit that situation and then open support tickets. If you want to build from source then you need to clone the repo.

**Comment by Anthchirp** [comment]
Okay, I have a working build in https://github.com/conda-forge/lensfunpy-feedstock/pull/6 using the github tag. If that is the correct way to obtain the sources then this ticket can be closed 👍
