### ISSUE TITLE
input data type and range?

### ISSUE THREAD

**Issue by ricsonc** [letmaik/lensfunpy#28]
What data type (uint8/uint16/float32/float64) is the input image expected to be in? In particular for `apply_color_modification`. Does the vignette correction happen in linear space, or after gamma / tone mapping?

My lens, Nikkor 80-200mm f/2.8 ED (w/ crop sensor), seems to be in the lensfun database as far as I can tell, but when I pass in float64 0-1 normalized linear data to `apply_color_modification`, I get nonsensical output range (max value gets set to 2.7e+155). When I pass in uint16 linear data, I get `*** TypeError: No matching signature found`.

**Comment by ricsonc** [comment]
Some progress: I found this page, https://lensfun.github.io/calibration-tutorial/lens-vignetting.html, which suggests linear space is correct

**Comment by ricsonc** [comment]
Ah, I missed that `lensfunpy.Modifier.initialize` has a `pixel_format` kwarg. Setting that correctly seems to fix all the weirdness

**Comment by letmaik** [comment]
The default img format is uint8, however you can use a different one when calling [`Modifier.initialize()`](https://letmaik.github.io/lensfunpy/api/lensfunpy.Modifier.html#lensfunpy.Modifier.initialize). I should probably add a check that the selected img format matches the one passed in apply_color_modification.  At least for uint8 the values are 0-255. I'm not sure if the range for float is 0-1.

**Comment by KelSolaar** [comment]
> Ah, I missed that `lensfunpy.Modifier.initialize` has a `pixel_format` kwarg. Setting that correctly seems to fix all the weirdness

This is a good note that should be documented I reckon. I was about to post an issue because I was seeing issues with `apply_color_modification` and turns out that they disappeared by setting the correct pixel format.

**Comment by letmaik** [comment]
> > Ah, I missed that `lensfunpy.Modifier.initialize` has a `pixel_format` kwarg. Setting that correctly seems to fix all the weirdness
> 
> This is a good note that should be documented I reckon. I was about to post an issue because I was seeing issues with `apply_color_modification` and turns out that they disappeared by setting the correct pixel format.

By all means, please submit a PR that documents this better! :)

**Comment by KelSolaar** [comment]
I will do, an also add an example on how to do TCA.
