### ISSUE TITLE
Installation failed on Jetson Xavier

### ISSUE THREAD

**Issue by danial880** [letmaik/lensfunpy#29]
I am installing lensfunpy on Jetson Xavier. I got the following error.
`sudo apt-get install libffi-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi-dev is already the newest version (3.2.1-8).
libffi-dev set to manually installed.
The following packages were automatically installed and are no longer required:
  python3-click python3-colorama
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
xavier@xavier-desktop:~/Downloads/lensfunpy-master$ sudo python3 setup.py install
Package lensfun was not found in the pkg-config search path.
Perhaps you should add the directory containing `lensfun.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lensfun' found
Package lensfun was not found in the pkg-config search path.
Perhaps you should add the directory containing `lensfun.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lensfun' found
Package lensfun was not found in the pkg-config search path.
Perhaps you should add the directory containing `lensfun.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lensfun' found
Package lensfun was not found in the pkg-config search path.
Perhaps you should add the directory containing `lensfun.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lensfun' found
Package lensfun was not found in the pkg-config search path.
Perhaps you should add the directory containing `lensfun.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lensfun' found
running install
running bdist_egg
running egg_info
writing lensfunpy.egg-info/PKG-INFO
writing dependency_links to lensfunpy.egg-info/dependency_links.txt
writing requirements to lensfunpy.egg-info/requires.txt
writing top-level names to lensfunpy.egg-info/top_level.txt
reading manifest file 'lensfunpy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'lensfunpy/version_helper.h'
writing manifest file 'lensfunpy.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-aarch64/egg
running install_lib
running build_py
running build_ext
building 'lensfunpy._lensfun' extension
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ilensfunpy -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/home/xavier/Downloads/lensfunpy-master/lensfunpy -I/usr/include/python3.6m -c lensfunpy/_lensfun.c -o build/temp.linux-aarch64-3.6/lensfunpy/_lensfun.o
In file included from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                 from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from lensfunpy/_lensfun.c:636:
/usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
lensfunpy/_lensfun.c:638:10: fatal error: lensfun.h: No such file or directory
 #include "lensfun.h"
          ^~~~~~~~~~~
compilation terminated.
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
`
I have tried with both i.e with pip and with setup.py but the same error occurs (fatal error: lensfun.h: No such file or directory)

**Comment by letmaik** [comment]
The message is quite clear. "Package lensfun was not found" It looks like you haven't followed the instructions in the readme which say "sudo apt-get install liblensfun-dev" if you want to build from source.
