### ISSUE TITLE
undefined symbol: lf_db_load_data

### ISSUE THREAD

**Issue by jcampbell05** [letmaik/lensfunpy#32]
I am currently following the build steps in the README to build lensfunpy for ARM on Amazon Lambda but I get this error message when using the library despite the library correctly loading.

These are the Dockerfile commands I am using 

```
RUN cd /tmp && \
    curl -o lensfun.tar.gz -L "https://github.com/lensfun/lensfun/tarball/v0.3.95" && \
    mkdir lensfun && \
    tar xvzf lensfun.tar.gz -C lensfun --strip-components 1 && \
    cd lensfun && \
    cmake . && \
    sudo make install && \
    echo "/usr/local/lib64" | sudo tee /etc/ld.so.conf.d/99local.conf && \
    sudo ldconfig
RUN PKG_CONFIG_PATH="/usr/local/lib64/pkgconfig/" pip install git+https://github.com/letmaik/lensfunpy --global-option="build_ext" --global-option="-I/usr/local/include/lensfun/"
```

I pass in the custom build arguments to the python package as otherwise it can't find the header files.

**Comment by letmaik** [comment]
Can you try using lensfun 0.3.3?
