### ISSUE TITLE
Only wheels uploaded to pypi for latest release

### ISSUE THREAD

**Issue by jcampbell05** [letmaik/lensfunpy#39]
According to PYPY only Wheels for Mac OS, Linux and Windows for AMD 64 are uploaded meaning anyone on any other setup like us cannot install latest version of this package without referencing the repo.

See here.
https://pypi.org/simple/lensfunpy/

**Comment by letmaik** [comment]
What's your platform?

**Comment by jcampbell05** [comment]
Our platform is ARM

**Comment by letmaik** [comment]
The latest release comes with ARM wheels, hopefully that solves your issue. See https://github.com/letmaik/lensfunpy/pull/41. Feel free to re-open if you still have problems.
