### ISSUE TITLE
Deprecated numpy API is used for testing

### ISSUE THREAD

**Issue by jia-kai** [letmaik/lensfunpy#46]
Hi,

I just created an AUR package for lensfunpy. During this I encountered an error about numpy import, which was caused by `test/test_basic.py` using [deprecated](https://numpy.org/doc/stable/release/1.25.0-notes.html) `numpy.testing.utils`. A patch is available [here](https://aur.archlinux.org/cgit/aur.git/tree/fix-test-np-import.patch?h=python-lensfunpy).

**Comment by letmaik** [comment]
Feel free to submit a PR :)

**Comment by jia-kai** [comment]
Surely! PR submitted :)

**Comment by letmaik** [comment]
Thanks!
